/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Элементы страницы
 */
export class Invitation {
  constructor(public id: string,
              /**
               * Код приглашения в группу
               */
              public code: string,
              /**
               * Количество использований кода
               */
              public usages: number,
              /**
               * Лимит на использование кода
               */
              public usageLimit: number,
              /**
               * Дата и время истечения приглашения
               */
              public expirationDateTime?: Date,
  ) {
  }
}
