/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {UsingTagDto} from '../tag/usingTagDto';

export class CreationVideoDto {
  public constructor(public title: string,
                     public description: string,
                     public recordingDateTime: Date,
                     public subjectId: string,
                     /**
                      * Используемые теги и используемые значения тегов в видео
                      */
                     public tags: UsingTagDto[],
  ) {
  }

}
