/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {TagDto} from '../tag/tagDto';
import {SubjectDto} from "../subject/subjectDto";

/**
 * Элементы страницы
 */
export class VideoDto {
  constructor(public id: string,
              public title: string,
              public description: string,
              /**
               * Дата создании видео (публикации его на сайт)
               */
              public creationDateTime: Date,
              /**
               * Дата записи лекции
               */
              public recordingDateTime: Date,
              /**
               * Используемые теги и используемые значения тегов в видео
               */
              public tags: TagDto[],
              public subject: SubjectDto,
              /**
               * Ссылка на VK видеоплеер
               */
              public playerUrl: string,
  ) {
  }

}
